### ISSUE TITLE
gatk: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/hellbender/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/CBI-software#101]
```sh
[dev2]$ gatk --list
Using GATK jar /wynton/home/cbi/shared/software/CBI/gatk-4.4.0.0/gatk-package-4.4.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /wynton/home/cbi/shar
ed/software/CBI/gatk-4.4.0.0/gatk-package-4.4.0.0-local.jar --help
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/scratch/hb
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/hellbender/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
```

**Comment by HenrikBengtsson** [comment]
This is because GATK (>= 4) requires a modern version of Java.  Java 11 LTS is not sufficient.  Java 17 LTS works, which is available on Rocky 8, but not CentOS 7.

I've updated the module to give an informative error message if a too old version of Java is used.
